[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.7.3", features = [ "derive" ] }
tokio = {version = "1.15.0", features = ["full"]}
wgpu = "0.12"
winit = "0.26"
